spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show:
        details: "always"

server:
  servlet:
    context-path: /api/v1/